"""add_minutes_and_minute_sections

Revision ID: 521e941480fb
Revises: 1f40476853f5
Create Date: 2026-07-31 23:06:57.179001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521e941480fb'
down_revision: Union[str, None] = '4b6d8e9f0a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    insp = sa.inspect(conn)
    # Idempotent : create_all de l'app peut avoir créé ces tables avant la migration
    if not insp.has_table("minutes"):
        op.create_table('minutes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('meeting_id', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('brouillon', 'valide', 'diffuse', name='minutestatus'), nullable=False, server_default='brouillon'),
        sa.Column('is_encrypted', sa.Boolean(), nullable=False, server_default=sa.text('0')),
        sa.Column('dek_version', sa.Integer(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('validated_by_id', sa.Integer(), nullable=True),
        sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_minutes_id'), 'minutes', ['id'], unique=False)
    if not insp.has_table("minute_sections"):
        op.create_table('minute_sections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('minute_id', sa.Integer(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('visibility', sa.Enum('interne', 'partage', name='sectionvisibility'), nullable=False, server_default='interne'),
        sa.Column('content', sa.LargeBinary(), nullable=False),
        sa.Column('nonce', sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(['minute_id'], ['minutes.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_minute_sections_id'), 'minute_sections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_minute_sections_id'), table_name='minute_sections')
    op.drop_table('minute_sections')
    op.drop_index(op.f('ix_minutes_id'), table_name='minutes')
    op.drop_table('minutes')
    # ### end Alembic commands ###
